package io.github.octaviusframework.driver.exception

/**
 * Exceptions generated by the database and translated by ExceptionTranslator.
 */

class DataOperationException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)

class ConstraintViolationException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)

class TransactionException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)

class PermissionDeniedException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)

class DatabaseSystemException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)
