package io.github.octaviusframework.driver.exception

/**
 * Exceptions generated by the database and translated by ExceptionTranslator.
 */



class TransactionException(
    message: String,
    cause: Throwable? = null,
    sqlState: String? = null
) : OctaviusException(message, cause, sqlState)




